runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:KDZS8BXpeLT8foelZ7T9WxJykAklBVc2MfANHKcyHsk=
  APP_DEBUG: true
  APP_LOG_LEVEL: debug
  APP_URL: https://final-project-cloud-apps.appspot.com

  DB_CONNECTION: mysql
  DB_HOST: 35.224.22.20
  DB_PORT: 3306
  DB_DATABASE: mipecera
  DB_USERNAME: root
  DB_PASSWORD: PCBgNJoCBJu0sy19
  DB_SOCKET: /cloudsql/final-project-cloud-apps:us-central1:mipecera

  MAIL_DRIVER: smtp
  MAIL_HOST: smtp.mailtrap.io
  MAIL_PORT: 2525

  INITIAL_USER_NAME: "Isaac Halabe"
  INITIAL_USER_EMAIL: "halabe15@gmail.com"
  INITIAL_USER_PASSWORDHASH: "$2y$10$pN.4v41dZKuOUXh2WcIjfOe23SESOmY/.uVgEgbHGykfTT5.pb4py"

beta_settings:
    cloud_sql_instances: final-project-cloud-apps:us-central1:mipecera
